### ISSUE TITLE
Which commit is supposed to work with UCX v1.9.0?

### ISSUE THREAD

**Issue by csehydrogen** [openucx/xucg#7]
With current master(ce03e43ff9aaf415135fc560ab9d2ccc0ad4edd0), I got the following error:
```
ucg_group.c: In function ‘ucg_collective_create’:
ucg_group.c:273:17: error: implicit declaration of function ‘ucs_cpu_cache_line_is_equal’ [-Werror=implicit-function-declaration]
  273 |             if (ucs_cpu_cache_line_is_equal(params, &op->params)) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ucg_group.c:273:17: error: nested extern declaration of ‘ucs_cpu_cache_line_is_equal’ [-Werror=nested-externs]
```

I walked up commits until compile succeeds(f67cd01728ff8f655b689602407a11ed3603e81f), but Segfault occurs if I try to use `ucg_context`. A bit of debugging shows that the bug resides in here:

https://github.com/openucx/xucg/blob/f67cd01728ff8f655b689602407a11ed3603e81f/base/ucg_context.c#L341-L356

Since `context_p` is reallocated to `tmp`, `tmp` should be used to init UCG context.

Or... Am I supposed to set `HAVE_UCP_EXTENSIONS`? I wonder what that flag means, since I cannot find the flag elsewhere(including UCX repository).

@alex--m If you know any stable commit known to work with UCX v1.9.0, please let me know.

Thanks in advance.

**Comment by alex--m** [comment]
@csehydrogen thank you for bringing this to my attention - I'll fix it later today (so it will build with UCX correctly).

To clarify, xUCG needs a LOT of modifications in UCX in order to get better performance, so for now - these changes are only available in my personal ["UCX for UCG" branch](https://github.com/alex--m/ucx/tree/topic/ucg-master) (this will change soon). The function `ucs_cpu_cache_line_is_equal` is one such modification. Since upstream UCG doesn't have them, I put them under "HAVE_UCP_EXTENSIONS" - which is '1' in my branch and undefined in upstream UCX.

**Comment by csehydrogen** [comment]
@alex--m Thanks, Alex. I'll look into your UCX fork.

One side question: Will it be OK to use xUCG for my project? I found at least 3 collective communication libraries in OpenUCX github: xucg, ucc, and xccl. I wonder which one is considered as a long-term candidate inside UCX community.

**Comment by alex--m** [comment]
@csehydrogen 

Yes, xUCG is open-source and everyone is welcome to use it (the license is the same as UCX). Regarding the libraries you found: xCCL is Mellanox's open-source collectives library (as opposed to their closed-source HCOLL), xUCG is Huawei's library, and UCC should eventually include both xUCG and xCCL (but is not working yet).

**Comment by csehydrogen** [comment]
Ok, I'll close this issue.

**Summary**
* For now, checkout [UCX for UCG branch](https://github.com/alex--m/ucx/tree/topic/ucg-master) to use UCG.

**Comment by alex--m** [comment]
@csehydrogen 
Actually, I just pushed a fix (72bb4ce) - it should be ok now.
